apiVersion: v1
kind: Service
metadata:
  namespace: default
  annotations:
  labels:
    app: grafana
  name: grafana
spec:
  type: LoadBalancer
  ports:
  - name: "webui"
    port: 3000
    targetPort: 3000
  - name: "webuistd"
    port: 80
    targetPort: 3000
  selector:
    app: grafana
status:
  loadBalancer: {}
