apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.14.100-10.0.14.255
      avoid-buggy-ips: true
    - name: reserved
      protocol: layer2
      addresses:
      - 10.0.14.5-10.0.14.99
      avoid-buggy-ips: true
      auto-assign: false
