apiVersion: v1
kind: Service
metadata:
  namespace: default
  annotations:
  labels:
    app: mariadb
  name: mariadb
spec:
  type: LoadBalancer
  ports:
  - name: "mariadb"
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
status:
  loadBalancer: {}
