apiVersion: v1
kind: Service
metadata:
  namespace: default
  annotations:
  labels:
    app: photoprism
  name: photoprism
spec:
  type: LoadBalancer
  ports:
  - name: "webui"
    port: 80
    targetPort: 80
  selector:
    app: photoprism
status:
  loadBalancer: {}
