apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: influxdb
  name: influxdb
spec:
  type: LoadBalancer
  ports:
  - name: "2003"
    port: 2003
    targetPort: 2003
  - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
status:
  loadBalancer: {}
